# Conditoions that have more than 45 comments
class Utils:

    conditions_controlled_by_psychiatrists = [
        "Depression",
        "Anxiety",
        "Bipolar Disorde",
        "Insomnia",
        "ADHD",
        "Anxiety and Stress",
        "Major Depressive Disorde",
        "Panic Disorde",
        "Generalized Anxiety Disorde",
        "Opiate Dependence",
        "Schizophrenia",
        "Obsessive Compulsive Disorde",
        "Schizoaffective Disorde",
        "Social Anxiety Disorde",
        "Alcohol Dependence",
        "Opiate Withdrawal",
        "Post Traumatic Stress Disorde",
        "Premenstrual Dysphoric Disorde",
        "Alcohol Withdrawal",
        "mance Anxiety",
        "Borderline Personality Disorde",
        "Autism",
        "Alzheimer's Disease",
        "Chronic Fatigue Syndrome",
        "Postpartum Depression",
        "Anorexia",
        "Binge Eating Disorde",
        "Sexual Dysfunction, SSRI Induced",
        "Hypersomnia",
        "Tourette's Syndrome",
        "Shift Work Sleep Disorde",
        "Bulimia",
        "Mania",
        "Paranoid Disorde",
        "Agitawted State",
    ]
